# Generated by Django 4.2 on 2023-04-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=355)),
                ('email', models.EmailField(max_length=355)),
                ('password', models.CharField(max_length=355)),
            ],
        ),
    ]
